[package]
name = "swarm-ir"
version = "0.1.0"
authors = ["iqbigbang <iqbigbang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libintern = "0.4"
wasm-encoder = "0.6"
# TODO: remove these, only used for testing
wasmprinter = "0.2"
wasmi = "0.9"